### ISSUE TITLE
Not on FX application thread; currentThread = pool-3-thread-1

### ISSUE THREAD

**Issue by demigord** [Sheep-y/trpg-dnd-4e-db#27]
Hi,

I installed Java 8 Update 111 (October 18, 2016) and ran 4e_compendium_downloader.exe

I am getting the error: Not on FX application thread; currentThread = pool-3-thread-1
Here is the debug log:

18:53:56 [FINE] Testing login finished normally.
18:53:56 [INFO] Status: Getting race template.
18:53:56 [FINE] Getting race template finished normally.
18:53:58 [INFO] Status: Getting race data.
18:53:58 [FINE] Getting race data finished normally.
18:53:59 [INFO] Status: Parsing race.
18:54:00 [INFO] Status: Listing race.
18:54:00 [FINE] Listing race finished normally.
18:54:00 [WARNING] Download failed: java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-3-thread-1
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at com.sun.javafx.webkit.prism.PrismInvoker.checkEventThread(PrismInvoker.java:62)
	at com.sun.webkit.dom.JSObject.getMember(JSObject.java:61)
	at db4e.controller.Crawler.toArray(Crawler.java:151)
	at db4e.controller.Crawler.openCategory(Crawler.java:105)
	at db4e.controller.Controller.downloadCategory(Controller.java:362)
	at db4e.controller.Controller.lambda$startDownload$9(Controller.java:334)
	at db4e.controller.Controller.lambda$runTask$21(Controller.java:496)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

18:54:00 [FINE] State: Can Download
18:54:00 [INFO] Status: Not on FX application thread; currentThread = pool-3-thread-1.
18:54:00 [FINE] Progress: 0.
18:54:09 [FINE] State: Can Export
18:54:09 [INFO] Status: null.

Thanks!

**Comment by Sheep-y** [comment]
Ah, That didn't exist in earlier Java versions when I still had a subscription, but I can see the wisdom in this new safeguard.

**Comment by demigord** [comment]
Let me know if I can do anything to help

**Comment by Sheep-y** [comment]
@demigord Can you try this [pre-release](https://github.com/Sheep-y/trpg-dnd-4e-db/releases/tag/rc%2F3.5.2.1) and see whether the download works now?
When you see the "Downloaded" counts go up, it should be all green.

**Comment by demigord** [comment]
Looks like it is working! Seemed to hang a couple of times (at loading Race and Poison Totals), but clicking on "Stop" got it going again. Left it running overnight and it is still downloading (halfway through Monsters now). Seems to have slowed down compared to when I started it (CPU usage is > 90%) but I am going to let it run.

Thanks a lot for the quick fix!
