### ISSUE TITLE
Error converting implement 113 Blue Orb of Dragonkind

### ISSUE THREAD

**Issue by mtvjr** [Sheep-y/trpg-dnd-4e-db#42]
When running with "Fix and Enhance Data" option, I get an "Error converting implement113 Blue Orb of Dragonkind" message.

Log:

```
10:06:54 [INFO] Exporting category Poison in thread pool-2-thread-7.
10:06:55 [WARNING] Export failed: java.lang.UnsupportedOperationException: Error converting implement113 Blue Orb of Dragonkind
	at db4e.converter.Convert.convert(Convert.java:419)
	at db4e.controller.Controller.lambda$exportEachCategory$27(Controller.java:675)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 5
	at db4e.data.Entry.getSimpleField(Entry.java:60)
	at db4e.converter.Converter.meta(Converter.java:436)
	at db4e.converter.ItemConverter.correctEntry(ItemConverter.java:377)
	at db4e.converter.Convert.convertEntry(Convert.java:457)
	at db4e.converter.Converter.convertEntry(Converter.java:47)
	at db4e.converter.ItemConverter.convertEntry(ItemConverter.java:61)
	at db4e.converter.Convert.convert(Convert.java:408)
	... 4 more

10:06:55 [INFO] Status: Error converting implement113 Blue Orb of Dragonkind.
```

![image](https://user-images.githubusercontent.com/9865643/41299407-fb99eef0-6e28-11e8-845b-21ef92e05852.png)

Exporting with "Fix and Enhance Data" disabled does not produce this error message.

**Comment by mtvjr** [comment]
Just realized this was a duplicate issue.

**Comment by Sheep-y** [comment]
Sorry I was busy working on other project and missed the first mail notification.

Yes it looks like a duplicate and can be solved by lowering thread count to 1.  I am aiming to release a new version this week that may fix the issue.

If you don't mind, may I know your PC's hardware configuration?

**Comment by mtvjr** [comment]
Sure, I have a Intel CPU 6700k, 16 GB RAM running Windows 10 insider 10.0.17134 Build 17134 with Java 1.8.0_171. This occurred on both the distributed EXE and build from source (Using Java SDK 1.8.0_171) using the latest master branch. I did not test the development branch, which I just now noticed exists.
